"""
Data Contracts for NZ Habitat Intelligence Pipeline.
Provides data provenance tracking and quality signals for each data artifact.
"""
from dataclasses import dataclass, field, asdict
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
import json
import logging
import pandas as pd
import numpy as np

logger = logging.getLogger(__name__)


class DataSource(Enum):
    """Classification of data source origin."""
    REAL = "real"           # From authenticated external API/scraping
    SYNTHETIC = "synthetic" # Generated by code (simulated/hardcoded)
    FALLBACK = "fallback"   # Hardcoded fallback when source fails
    PROXY = "proxy"         # Used as proxy for actual data (e.g., World Bank as NZ proxy)
    UNKNOWN = "unknown"     # Cannot be determined


class DataQuality(Enum):
    """Overall data quality classification."""
    EXCELLENT = "excellent" # Real data, no nulls, validated
    GOOD = "good"           # Real data, minor gaps
    FAIR = "fair"           # Real data with significant gaps or synthetic
    POOR = "poor"           # Mostly synthetic/fallback
    UNKNOWN = "unknown"     # Cannot determine


@dataclass
class ColumnContract:
    """Contract for a single column in a dataset."""
    name: str
    dtype: str
    null_count: int = 0
    null_percentage: float = 0.0
    unique_count: int = 0
    min_value: Optional[Any] = None
    max_value: Optional[Any] = None
    sample_values: List[Any] = field(default_factory=list)


@dataclass
class DataContract:
    """
    Contract metadata for a data artifact (Bronze/Silver/Gold layer).

    This provides clear signal to consumers about data origin and quality,
    preventing silent mixing of real and synthetic data.
    """
    # Identity (required, no defaults)
    artifact_name: str
    artifact_path: str
    layer: str  # 'bronze', 'silver', 'gold'

    # Provenance (required, no defaults)
    source: DataSource
    source_name: str  # e.g., 'world_bank_api', 'rbnz_csv', 'synthetic_generator'

    # All other fields have defaults
    source_url: Optional[str] = None
    quality: DataQuality = DataQuality.UNKNOWN
    confidence_score: float = 0.0
    record_count: int = 0
    column_count: int = 0
    null_percentage: float = 0.0
    columns: List[ColumnContract] = field(default_factory=list)
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    data_from_date: Optional[str] = None
    data_to_date: Optional[str] = None

    # Provenance chain
    parent_contracts: List[str] = field(default_factory=list)  # Paths to parent contracts

    # Notes
    notes: str = ""

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary, handling enum serialization."""
        d = asdict(self)
        d['source'] = self.source.value
        d['quality'] = self.quality.value
        # Convert column contracts to dict format
        columns_list = []
        for col in d.get('columns', []):
            if isinstance(col, ColumnContract):
                col_dict = asdict(col)
                columns_list.append(col_dict)
            elif isinstance(col, dict):
                columns_list.append(col)
            else:
                columns_list.append(col)
        d['columns'] = columns_list
        return d

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> 'DataContract':
        """Create from dictionary with enum parsing."""
        d['source'] = DataSource(d['source'])
        d['quality'] = DataQuality(d['quality'])
        return cls(**d)

    def save(self, path: Optional[Path] = None) -> str:
        """Save contract to JSON file."""
        if path is None:
            path = Path(self.artifact_path)

        path_str = str(path)
        # Ensure .contract.json suffix
        if not path_str.endswith('.contract.json'):
            if '.' in path_str:
                path = path.with_suffix('.contract.json')
            else:
                path = Path(path_str + '.contract.json')

        with open(path, 'w', encoding='utf-8') as f:
            json.dump(self.to_dict(), f, indent=2, default=str)

        return str(path)

    @classmethod
    def load(cls, path: str) -> 'DataContract':
        """Load contract from JSON file."""
        with open(path, 'r', encoding='utf-8') as f:
            return cls.from_dict(json.load(f))

    @property
    def is_trusted(self) -> bool:
        """Check if data meets minimum confidence threshold."""
        return self.confidence_score >= 70.0 and self.source != DataSource.SYNTHETIC

    def get_summary(self) -> str:
        """Get human-readable summary."""
        return (
            f"{self.artifact_name} ({self.layer}): "
            f"{self.record_count} records, "
            f"source={self.source.value}, "
            f"quality={self.quality.value}, "
            f"confidence={self.confidence_score:.0f}%"
        )


def detect_data_source(df: pd.DataFrame, source_name: str = "unknown") -> DataSource:
    """
    Detect if DataFrame contains real or synthetic data.

    Uses heuristics:
    1. Check for low unique ratio (repeated values = synthetic)
    2. Check for perfect round numbers (hardcoded)
    3. Check data freshness (recent dates = likely synthetic)
    4. Check source name patterns

    Args:
        df: DataFrame to analyze
        source_name: Name of source for context

    Returns:
        DataSource classification
    """
    if df.empty:
        return DataSource.UNKNOWN

    # Pattern 1: Low entropy - same values repeated
    if len(df) > 10:
        max_unique_ratio = 0
        for col in df.columns:
            if df[col].dtype in ['int64', 'float64']:
                unique_ratio = df[col].nunique() / len(df)
                max_unique_ratio = max(max_unique_ratio, unique_ratio)

        # Synthetic data often has low unique ratio (repeated values)
        if max_unique_ratio < 0.3:
            return DataSource.SYNTHETIC

    # Pattern 2: Perfect round numbers (hardcoded)
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    for col in numeric_cols:
        # Check if values are "too round" (multiples of common amounts)
        values = df[col].dropna()
        if len(values) > 5:
            # Common in synthetic: multiples of 100, 1000, etc.
            round_pct = (values % 100 == 0).mean()
            if round_pct > 0.8:
                return DataSource.SYNTHETIC

    # Pattern 3: All dates are recent (last 3 years)
    date_cols = ['date', 'year', 'month', 'timestamp']
    for col in date_cols:
        if col in df.columns:
            if col == 'year' and df['year'].dtype in ['int64', 'float64']:
                current_year = datetime.now().year
                recent_years = df[df['year'] >= current_year - 3]['year']
                if len(recent_years) == len(df) and len(df) < 50:
                    # Small dataset with only recent years = likely synthetic
                    return DataSource.SYNTHETIC

    # Pattern 4: World Bank API data is reliable real data
    if 'world_bank' in source_name.lower():
        return DataSource.REAL

    # Pattern 5: Government APIs (stats_nz, rbnz, etc.) are real
    government_sources = ['stats_nz', 'rbnz', 'linz', 'mbie', 'oecd']
    for gov_src in government_sources:
        if gov_src in source_name.lower():
            return DataSource.REAL

    # Default: assume real if from known source, unknown otherwise
    return DataSource.UNKNOWN


def analyze_dataframe(df: pd.DataFrame, artifact_name: str) -> Dict[str, Any]:
    """
    Perform comprehensive analysis of a DataFrame.

    Args:
        df: DataFrame to analyze
        artifact_name: Name for artifact context

    Returns:
        Dictionary with analysis results
    """
    if df.empty:
        return {
            'record_count': 0,
            'column_count': 0,
            'null_percentage': 100.0,
            'columns': [],
            'data_from_date': None,
            'data_to_date': None
        }

    total_cells = df.shape[0] * df.shape[1]
    null_cells = df.isnull().sum().sum()

    # Analyze columns
    column_contracts = []
    for col in df.columns:
        col_data = df[col]
        null_count = col_data.isnull().sum()

        col_contract = ColumnContract(
            name=col,
            dtype=str(col_data.dtype),
            null_count=int(null_count),
            null_percentage=float(null_count / len(df) * 100) if len(df) > 0 else 0.0,
            unique_count=int(col_data.nunique()),
            min_value=float(col_data.min()) if col_data.dtype in ['int64', 'float64'] else None,
            max_value=float(col_data.max()) if col_data.dtype in ['int64', 'float64'] else None,
            sample_values=col_data.dropna().head(5).tolist()
        )
        column_contracts.append(col_contract)

    # Detect date range
    data_from_date = None
    data_to_date = None

    if 'year' in df.columns:
        years = pd.to_numeric(df['year'], errors='coerce').dropna()
        if len(years) > 0:
            data_from_date = f"{int(years.min())}-01-01"
            data_to_date = f"{int(years.max())}-12-31"

    if 'date' in df.columns:
        try:
            dates = pd.to_datetime(df['date'], errors='coerce').dropna()
            if len(dates) > 0:
                data_from_date = dates.min().strftime('%Y-%m-%d')
                data_to_date = dates.max().strftime('%Y-%m-%d')
        except Exception as e:
            logger.warning(f"Could not parse dates for contract: {e}")

    return {
        'record_count': len(df),
        'column_count': len(df.columns),
        'null_percentage': float(null_cells / total_cells * 100) if total_cells > 0 else 0.0,
        'columns': column_contracts,
        'data_from_date': data_from_date,
        'data_to_date': data_to_date
    }


def calculate_confidence_score(
    df: pd.DataFrame,
    source: DataSource,
    null_percentage: float
) -> float:
    """
    Calculate confidence score (0-100) for a DataFrame.

    Factors:
    - Source type (real = 50 base, synthetic = 0 base)
    - Null percentage (lower is better)
    - Data freshness (has recent real data)
    - Column completeness

    Args:
        df: DataFrame to evaluate
        source: Data source classification
        null_percentage: Percentage of null values

    Returns:
        Confidence score from 0 to 100
    """
    if df.empty:
        return 0.0

    score = 0.0

    # Base score from source
    if source == DataSource.REAL:
        score += 50
    elif source == DataSource.PROXY:
        score += 35
    elif source == DataSource.FALLBACK:
        score += 10
    elif source == DataSource.SYNTHETIC:
        score += 0
    else:  # UNKNOWN
        score += 15

    # Null penalty (0-30 points)
    if null_percentage < 5:
        score += 30
    elif null_percentage < 15:
        score += 20
    elif null_percentage < 30:
        score += 10
    else:
        score += 0

    # Data completeness (0-15 points)
    row_complete_pct = 100 - null_percentage
    if row_complete_pct > 95:
        score += 15
    elif row_complete_pct > 85:
        score += 10
    elif row_complete_pct > 70:
        score += 5

    # Record count bonus (0-5 points)
    if len(df) >= 100:
        score += 5
    elif len(df) >= 50:
        score += 3
    elif len(df) >= 20:
        score += 1

    return min(100.0, max(0.0, score))


def get_data_quality(null_percentage: float, confidence_score: float, source: DataSource) -> DataQuality:
    """
    Determine overall data quality classification.

    Args:
        null_percentage: Percentage of null values
        confidence_score: Calculated confidence score
        source: Data source classification

    Returns:
        DataQuality classification
    """
    if confidence_score >= 85 and source == DataSource.REAL and null_percentage < 5:
        return DataQuality.EXCELLENT
    elif confidence_score >= 70 and source in [DataSource.REAL, DataSource.PROXY]:
        return DataQuality.GOOD
    elif confidence_score >= 50:
        return DataQuality.FAIR
    elif confidence_score >= 25:
        return DataQuality.POOR
    else:
        return DataQuality.UNKNOWN


def create_contract(
    df: pd.DataFrame,
    artifact_name: str,
    artifact_path: str,
    layer: str,
    source: DataSource,
    source_name: str,
    source_url: Optional[str] = None,
    parent_contracts: Optional[List[str]] = None,
    notes: str = ""
) -> DataContract:
    """
    Create a complete DataContract for a DataFrame.

    This is the main entry point for creating contracts.

    Args:
        df: DataFrame to create contract for
        artifact_name: Name identifier for this artifact
        artifact_path: Path where artifact is/will be stored
        layer: Pipeline layer ('bronze', 'silver', 'gold')
        source: Classification of data source
        source_name: Human-readable source name
        source_url: URL or path to source (optional)
        parent_contracts: List of parent contract paths (optional)
        notes: Additional notes (optional)

    Returns:
        DataContract instance
    """
    # Analyze the dataframe
    analysis = analyze_dataframe(df, artifact_name)

    # Convert column contracts to dict format
    column_contracts = []
    for col in analysis['columns']:
        if isinstance(col, ColumnContract):
            column_contracts.append(asdict(col))
        else:
            column_contracts.append(col)

    # Calculate confidence and quality
    confidence = calculate_confidence_score(df, source, analysis['null_percentage'])
    quality = get_data_quality(analysis['null_percentage'], confidence, source)

    # If source was UNKNOWN, use auto-detection
    if source == DataSource.UNKNOWN:
        detected_source = detect_data_source(df, source_name)
        if detected_source != DataSource.UNKNOWN:
            source = detected_source
            confidence = calculate_confidence_score(df, source, analysis['null_percentage'])
            quality = get_data_quality(analysis['null_percentage'], confidence, source)

    return DataContract(
        artifact_name=artifact_name,
        artifact_path=artifact_path,
        layer=layer,
        source=source,
        source_name=source_name,
        source_url=source_url,
        quality=quality,
        confidence_score=confidence,
        record_count=analysis['record_count'],
        column_count=analysis['column_count'],
        null_percentage=analysis['null_percentage'],
        columns=column_contracts,
        data_from_date=analysis['data_from_date'],
        data_to_date=analysis['data_to_date'],
        parent_contracts=parent_contracts or [],
        notes=notes
    )


def validate_schema(
    df: pd.DataFrame,
    required_columns: List[str],
    column_types: Optional[Dict[str, str]] = None
) -> Tuple[bool, List[str]]:
    """
    Validate DataFrame schema against expected contract.

    Args:
        df: DataFrame to validate
        required_columns: List of column names that must exist
        column_types: Optional dict of column -> expected dtype

    Returns:
        Tuple of (is_valid, list_of_errors)
    """
    errors = []

    # Check required columns exist
    missing = set(required_columns) - set(df.columns)
    if missing:
        errors.append(f"Missing required columns: {', '.join(missing)}")

    # Check column types if specified
    if column_types:
        for col, expected_type in column_types.items():
            if col in df.columns:
                actual_type = str(df[col].dtype)
                if expected_type not in actual_type:
                    errors.append(f"Column '{col}' has type '{actual_type}', expected '{expected_type}'")

    return len(errors) == 0, errors


def save_dataframe_with_contract(
    df: pd.DataFrame,
    path: str,
    artifact_name: str,
    layer: str,
    source: DataSource,
    source_name: str,
    source_url: Optional[str] = None,
    parent_contracts: Optional[List[str]] = None,
    notes: str = ""
) -> Tuple[str, str]:
    """
    Save DataFrame and its contract together.

    Args:
        df: DataFrame to save
        path: Base path for the artifact (without extension)
        artifact_name: Name identifier for this artifact
        layer: Pipeline layer ('bronze', 'silver', 'gold')
        source: Classification of data source
        source_name: Human-readable source name
        source_url: Source URL (optional)
        parent_contracts: Parent contract paths (optional)
        notes: Additional notes (optional)

    Returns:
        Tuple of (parquet_path, contract_path)
    """
    path = Path(path)
    parquet_path = str(path.with_suffix('.parquet'))
    contract_path = str(path.with_suffix('.contract.json'))

    # Save DataFrame
    df.to_parquet(parquet_path, index=False)

    # Create and save contract
    contract = create_contract(
        df=df,
        artifact_name=artifact_name,
        artifact_path=parquet_path,
        layer=layer,
        source=source,
        source_name=source_name,
        source_url=source_url,
        parent_contracts=parent_contracts,
        notes=notes
    )
    contract.save(Path(contract_path))

    return parquet_path, contract_path


def load_with_contract(path: str) -> Tuple[pd.DataFrame, Optional[DataContract]]:
    """
    Load DataFrame and its contract together.

    Args:
        path: Path to parquet file

    Returns:
        Tuple of (DataFrame, DataContract or None if no contract)
    """
    df = pd.read_parquet(path)

    contract_path = str(Path(path).with_suffix('.contract.json'))
    contract = None

    if Path(contract_path).exists():
        try:
            contract = DataContract.load(contract_path)
        except Exception as e:
            logger.warning(f"Could not load contract from {contract_path}: {e}")

    return df, contract


def get_layer_contracts(layer_dir: str, layer: str) -> List[DataContract]:
    """
    Load all contracts for a pipeline layer.

    Args:
        layer_dir: Directory containing layer artifacts
        layer: Layer name ('bronze', 'silver', 'gold')

    Returns:
        List of DataContract objects found in the directory
    """
    contracts = []
    layer_path = Path(layer_dir)

    if not layer_path.exists():
        return contracts

    # Find all contract files
    for contract_file in layer_path.glob('**/*.contract.json'):
        try:
            contract = DataContract.load(str(contract_file))
            contracts.append(contract)
        except Exception as e:
            logger.warning(f"Could not load contract {contract_file}: {e}")
            continue

    return contracts


def generate_quality_report(layer_dirs: Dict[str, str]) -> Dict[str, Any]:
    """
    Generate a quality report for all pipeline layers.

    Args:
        layer_dirs: Dict mapping layer name to directory path
                   e.g., {'bronze': 'data/bronze', 'silver': 'data/silver', 'gold': 'data/gold'}

    Returns:
        Dictionary with quality report
    """
    report = {
        'generated_at': datetime.now().isoformat(),
        'layers': {},
        'artifacts_total': 0,
        'overall_quality_score': 0.0
    }

    total_score = 0.0
    total_contracts = 0

    for layer_name, layer_dir in layer_dirs.items():
        contracts = get_layer_contracts(layer_dir, layer_name)

        layer_stats = {
            'artifact_count': len(contracts),
            'sources': {},
            'quality_distribution': {},
            'avg_confidence': 0.0
        }

        source_counts = {}
        quality_counts = {}
        confidence_sum = 0.0

        for contract in contracts:
            # Count by source
            source_key = contract.source.value
            source_counts[source_key] = source_counts.get(source_key, 0) + 1

            # Count by quality
            quality_key = contract.quality.value
            quality_counts[quality_key] = quality_counts.get(quality_key, 0) + 1

            # Sum confidence
            confidence_sum += contract.confidence_score
            total_score += contract.confidence_score
            total_contracts += 1

        layer_stats['sources'] = source_counts
        layer_stats['quality_distribution'] = quality_counts
        layer_stats['avg_confidence'] = confidence_sum / len(contracts) if contracts else 0.0

        report['layers'][layer_name] = layer_stats
        report['artifacts_total'] += len(contracts)

    report['overall_quality_score'] = total_score / total_contracts if total_contracts > 0 else 0.0

    return report